name: signalr_socket
description: "A flutter plugin for aspx.net SignalR client for Android, iOS, macOS and Web"
version: 1.1.6
homepage: https://github.com/ARASHz4/signalr_socket_flutter

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  js: ^0.7.1

  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arashz4.signalr_socket
        pluginClass: SignalrSocketPlugin
      ios:
        pluginClass: SignalrSocketPlugin
      macos:
        pluginClass: SignalrSocketPlugin
      web:
        pluginClass: SignalrSocketWeb
        fileName: signalr_socket_web.dart
