name: signalr_socket
description: A flutter plugin for aspx.net SignalR client for Android, iOS, macOS and Web
version: 1.1.4
homepage: https://github.com/ARASHz4/signalr_socket_flutter

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.4
  flutter_js: ^0.6.0

  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arashz4.signalr_socket
        pluginClass: SignalrSocketPlugin
      ios:
        pluginClass: SignalrSocketPlugin
      macos:
        pluginClass: SignalrSocketPlugin
      web:
        pluginClass: SignalrSocketWeb
        fileName: signalr_socket_web.dart
      windows:
        pluginClass: SignalrSocketPluginCApi
      linux:
        pluginClass: SignalrSocketPlugin

  assets:
    - packages/signalr_socket/js/jquery.min.js
    - packages/signalr_socket/js/jquery.signalR-2.4.3.min.js
    - packages/signalr_socket/js/socketConnection.js
