name: signalr_socket
description: SignalR Socket for Flutter
version: 1.0.8
homepage: https://github.com/ARASHz4/signalr_socket_flutter

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.4

  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arashz4.signalr_socket
        pluginClass: SignalrSocketPlugin
      ios:
        pluginClass: SignalrSocketPlugin
      macos:
        pluginClass: SignalrSocketPlugin
      web:
        pluginClass: SignalrSocketWeb
        fileName: signalr_socket_web.dart
